version: '3'

services:
  server:
    container_name: app_cont
    build: ./part5
  proxy:
    container_name: proxy_cont
    image: nginx
    volumes:
      - ./part6/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
